name: Dump
on: push
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: ./.github/actions/dump/ # ローカルアクションの呼び出し
        id: dump # 出力値参照のためステップIDを定義
        with:
          enable-context: "true" # 入力パラメータの指定

      - run: echo "${DATE}"
        env:
          DATE: ${{ steps.dump.outputs.dumped-date }} # アクションの出力値を参照
