name: Dump
on: push
jobs:
  debug: # "debug" はジョブ名です
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/dump/ # ローカルアクションの呼び出し
        id: dump # 出力値参照のためステップIDを定義
        with:
          enable-context: "true" # 入力パラメータの指定

      - run: echo "${DATE}"
        env:
          DATE: ${{ steps.dump.outputs.dumped-date }} # アクションの出力値を参照
